version: "3"
services:
  db:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
  gateway:
    container_name: gateway
    build: ./GatewayService/
    restart: on-failure
    volumes:
      - ./GatewayService/:/GatewayService/
    ports:
      - '8080:8080'
  ticket:
    container_name: ticket
    build: ./TicketService/
    restart: on-failure
    volumes:
      - ./TicketService/:/TicketService/
    ports:
      - '8070:8070'
  flight:
    container_name: flight
    build: ./FlightService/
    restart: on-failure
    volumes:
      - ./FlightService/:/FlightService/
    ports:
      - '8060:8060'
  bonus:
    container_name: bonus
    build: ./BonusService/
    restart: on-failure
    volumes:
      - ./BonusService/:/BonusService/
    ports:
      - '8050:8050'
    depends_on:
      - db

# TODO добавить сервисы

volumes:
  db-data: