{{ if .Values.service.isGateway }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress-service
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-ingress-service
    app.kubernetes.io/version: "{{ .Values.service.image.version }}"
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: lab4
    app.kubernetes.io/managed-by: helm
spec:
  ingressClassName: contour
  rules:
    - host: {{ .Chart.Name }}.{{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}
                port:
                  number: {{ .Values.service.port }}
{{- end}}