# Generated by Django 4.1.2 on 2022-10-16 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('country', models.CharField(max_length=255, verbose_name='Страна')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20, verbose_name='Номер рейса')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('from_airport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airportFrom', to='flight.airport')),
                ('to_airport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airportTo', to='flight.airport')),
            ],
        ),
    ]
