# Generated by Django 4.1.2 on 2022-10-16 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='from_airport_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_airport_id', to='flight.airport'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='to_airport_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_airport_id', to='flight.airport'),
        ),
    ]
