# Generated by Django 4.1.2 on 2022-10-16 15:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_uid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='ID билета')),
                ('username', models.CharField(max_length=80, verbose_name='Пользователь')),
                ('flight_number', models.CharField(max_length=20, verbose_name='Номер рейса')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('CANCELED', 'Canceled')], max_length=20, verbose_name='Статус')),
            ],
        ),
    ]
