# Generated by Django 4.1.2 on 2022-10-16 15:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80, unique=True, verbose_name='Пользователь')),
                ('status', models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold')], default='BRONZE', max_length=80, null=True, verbose_name='Статус')),
                ('balance', models.IntegerField(verbose_name='Баланс')),
            ],
        ),
        migrations.CreateModel(
            name='PrivilegeHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_uid', models.UUIDField(default=uuid.uuid4, verbose_name='ID билета')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время')),
                ('balance_diff', models.IntegerField(verbose_name='Разница баланса')),
                ('operation_type', models.CharField(choices=[('FILL_IN_BALANCE', 'Fill in balance'), ('DEBIT_THE_ACCOUNT', 'Debit the account')], max_length=20, verbose_name='Тип операции')),
                ('privilege_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonus.privilege')),
            ],
        ),
    ]
