name: GitHub Classroom Workflow
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      - name: DockerHub
        run: |
          docker-compose build
          docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_PASS }}
          docker-compose push
      - name: Kubectl
        uses: Azure/setup-kubectl@v3.1

      - name: Kubectl conf
        run: |
          mkdir $HOME/.kube
          ls -la $HOME/.kube
          cp ./k8s/config $HOME/.kube/config
          kubectl cluster-info dump
      - name: Deploy Helm
        run: |
          echo "HELM 1"
          helm delete databases
          helm install databases k8s/postgres-chart
          echo "HELM 2"
          helm delete services
          helm install services k8s/services-chart
          sleep 30

      - name: Keycloak in Docker
        run: docker run -p 8002:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:20.0.2 start-dev

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v1/postman/collection.json
          environment: v1/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 5
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"